export const SEND_SEARCH = 'SEND_SEARCH';
export const REJECT_BUTTON = 'REJECT_BUTTON';
export const ACCEPT_BUTTON = 'ACCEPT_BUTTON';
export const FAVOURITES_BUTTON = 'FAVOURITES_BUTTON';
export const FAVOURITES_LIST = 'FAVOURITES_LIST';
export const HOME = 'HOME';

